## Data Cleaning in Pandas

In [30]:
import pandas as pd

In [31]:
df = pd.read_csv(r"/Users/darllabulagner/Desktop/SQL THINGS/CSV FILES/Coffee_Chain_Sales .csv")
df

,Area Code,Cogs,DifferenceBetweenActualandTargetProfit,Date,Inventory Margin,Margin,Market_size,Market,Product_line,Product_type,Product,Profit,Sales,State,Target_cogs,Target_margin,Target_profit,Target_sales,Total_expenses,Type
0,303,51,-35,10/1/12,503,71,Major Market,Central,Leaves,Herbal Tea,Lemon,-5,122,Colorado,30,60,30,90,76,Decaf
1,970,52,-24,10/1/12,405,71,Major Market,Central,Leaves,Herbal Tea,Mint,26,123,Colorado,30,60,50,90,45,Decaf
2,409,43,-22,10/2/12,419,64,Major Market,South,Leaves,Herbal Tea,Lemon,28,107,Texas,30,60,50,90,36,Decaf
3,850,38,-15,10/3/12,871,56,Major Market,East,Leaves,Tea,Darjeeling,35,94,Florida,40,60,50,100,21,Regular
4,562,72,6,10/4/12,650,110,Major Market,West,Leaves,Tea,Green Tea,56,182,California,20,60,50,80,54,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057,775,250,133,8/23/15,1820,251,Small Market,West,Leaves,Tea,Earl Grey,233,534,Nevada,180,180,100,360,94,Regular
1058,971,88,48,8/24/15,817,133,Small Market,West,Leaves,Tea,Earl Grey,108,236,Oregon,60,100,60,160,60,Regular
1059,775,294,-285,8/25/15,8252,-294,Small Market,West,Leaves,Tea,Green Tea,-605,33,Nevada,210,-210,-320,0,145,Regular
1060,503,134,80,8/26/15,690,186,Small Market,West,Leaves,Tea,Green Tea,180,341,Oregon,90,140,100,230,65,Regular
1061,435,20,-22,8/27/15,218,25,Small Market,West,Leaves,Tea,Green Tea,-22,48,Utah,10,20,0,30,40,Regular

In [50]:
df = df.drop_duplicates()
df

,Area Code,Cogs,Date,Inventory Margin,Margin,Market_size,Market,Product_line,Product_type,Product,Profit,Sales,State,Target_cogs,Target_margin,Target_profit,Target_sales,Total_expenses,Type
0,303,51,10/1/12,503,71,Major Market,Central,Leaves,Herbal Tea,Lemon,-5,122,Colorado,30,60,30,90,76,Decaf
1,970,52,10/1/12,405,71,Major Market,Central,Leaves,Herbal Tea,Mint,26,123,Colorado,30,60,50,90,45,Decaf
2,409,43,10/2/12,419,64,Major Market,South,Leaves,Herbal Tea,Lemon,28,107,Texas,30,60,50,90,36,Decaf
3,850,38,10/3/12,871,56,Major Market,East,Leaves,Tea,Darjeeling,35,94,Florida,40,60,50,100,21,Regular
4,562,72,10/4/12,650,110,Major Market,West,Leaves,Tea,Green Tea,56,182,California,20,60,50,80,54,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057,775,250,8/23/15,1820,251,Small Market,West,Leaves,Tea,Earl Grey,233,534,Nevada,180,180,100,360,94,Regular
1058,971,88,8/24/15,817,133,Small Market,West,Leaves,Tea,Earl Grey,108,236,Oregon,60,100,60,160,60,Regular
1059,775,294,8/25/15,8252,-294,Small Market,West,Leaves,Tea,Green Tea,-605,33,Nevada,210,-210,-320,0,145,Regular
1060,503,134,8/26/15,690,186,Small Market,West,Leaves,Tea,Green Tea,180,341,Oregon,90,140,100,230,65,Regular
1061,435,20,8/27/15,218,25,Small Market,West,Leaves,Tea,Green Tea,-22,48,Utah,10,20,0,30,40,Regular

In [54]:
df = df.drop(columns = "Cogs")
df

,Area Code,Date,Inventory Margin,Margin,Market_size,Market,Product_line,Product_type,Product,Profit,Sales,State,Target_cogs,Target_margin,Target_profit,Target_sales,Total_expenses,Type
0,303,10/1/12,503,71,Major Market,Central,Leaves,Herbal Tea,Lemon,-5,122,Colorado,30,60,30,90,76,Decaf
1,970,10/1/12,405,71,Major Market,Central,Leaves,Herbal Tea,Mint,26,123,Colorado,30,60,50,90,45,Decaf
2,409,10/2/12,419,64,Major Market,South,Leaves,Herbal Tea,Lemon,28,107,Texas,30,60,50,90,36,Decaf
3,850,10/3/12,871,56,Major Market,East,Leaves,Tea,Darjeeling,35,94,Florida,40,60,50,100,21,Regular
4,562,10/4/12,650,110,Major Market,West,Leaves,Tea,Green Tea,56,182,California,20,60,50,80,54,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057,775,8/23/15,1820,251,Small Market,West,Leaves,Tea,Earl Grey,233,534,Nevada,180,180,100,360,94,Regular
1058,971,8/24/15,817,133,Small Market,West,Leaves,Tea,Earl Grey,108,236,Oregon,60,100,60,160,60,Regular
1059,775,8/25/15,8252,-294,Small Market,West,Leaves,Tea,Green Tea,-605,33,Nevada,210,-210,-320,0,145,Regular
1060,503,8/26/15,690,186,Small Market,West,Leaves,Tea,Green Tea,180,341,Oregon,90,140,100,230,65,Regular
1061,435,8/27/15,218,25,Small Market,West,Leaves,Tea,Green Tea,-22,48,Utah,10,20,0,30,40,Regular

In [55]:
df.columns

Index(['Area Code', 'Date', 'Inventory Margin', 'Margin', 'Market_size',
       'Market', 'Product_line', 'Product_type', 'Product', 'Profit', 'Sales',
       'State', 'Target_cogs', 'Target_margin', 'Target_profit',
       'Target_sales ', 'Total_expenses', 'Type'],
      dtype='object')

In [56]:
df = df.reset_index(drop=True)
df

,Area Code,Date,Inventory Margin,Margin,Market_size,Market,Product_line,Product_type,Product,Profit,Sales,State,Target_cogs,Target_margin,Target_profit,Target_sales,Total_expenses,Type
0,303,10/1/12,503,71,Major Market,Central,Leaves,Herbal Tea,Lemon,-5,122,Colorado,30,60,30,90,76,Decaf
1,970,10/1/12,405,71,Major Market,Central,Leaves,Herbal Tea,Mint,26,123,Colorado,30,60,50,90,45,Decaf
2,409,10/2/12,419,64,Major Market,South,Leaves,Herbal Tea,Lemon,28,107,Texas,30,60,50,90,36,Decaf
3,850,10/3/12,871,56,Major Market,East,Leaves,Tea,Darjeeling,35,94,Florida,40,60,50,100,21,Regular
4,562,10/4/12,650,110,Major Market,West,Leaves,Tea,Green Tea,56,182,California,20,60,50,80,54,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057,775,8/23/15,1820,251,Small Market,West,Leaves,Tea,Earl Grey,233,534,Nevada,180,180,100,360,94,Regular
1058,971,8/24/15,817,133,Small Market,West,Leaves,Tea,Earl Grey,108,236,Oregon,60,100,60,160,60,Regular
1059,775,8/25/15,8252,-294,Small Market,West,Leaves,Tea,Green Tea,-605,33,Nevada,210,-210,-320,0,145,Regular
1060,503,8/26/15,690,186,Small Market,West,Leaves,Tea,Green Tea,180,341,Oregon,90,140,100,230,65,Regular
1061,435,8/27/15,218,25,Small Market,West,Leaves,Tea,Green Tea,-22,48,Utah,10,20,0,30,40,Regular